apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: donation-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: solidarytech
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/brianmonteiro54/deploy-donation-service.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: solidarytech-donation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
